FROM python:3.13-slim
LABEL developed_by='@LeoAlecksey'
WORKDIR /usr/src/app
COPY ./requirements.txt .
RUN apt-get update && apt-get install -y --no-install-recommends curl
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
COPY ./docker_metricks.py .
CMD ["python3", "/usr/src/app/docker_metricks.py"]
